---
- name: Deploy Apache Docker Container
  hosts: local
  tasks:
    - name: Deploy Apache Docker container
      docker_container:
        name: apache_container
        image: httpd:latest
        state: started
        ports:
          - "80:80"
    - name: Configure Networking for Apache Container
      command: ip addr add 172.168.10.2/30 dev eth0
      when: ansible_hostname == "localhost"
